'Type: Dependencies':
- any:
    - changed-files:
        - any-glob-to-any-file: 'requirements/stratify.yml'
        - any-glob-to-any-file: 'requirements/py*.yml'
        - any-glob-to-any-file: 'requirements/locks/pypi*.txt'
        - any-glob-to-any-file: 'requirements/locks/py*.lock'

'Type: Documentation':
- any:
    changed-files:
      - any-glob-to-any-file: 'index.ipynb'
      - any-glob-to-any-file: 'README.md'

'Type: GHA':
- any:
    - changed-files:
        - any-glob-to-any-file: '.github/*.yml'
        - any-glob-to-any-file: '.github/**/*.yml'

'Type: Infrastructure':
- any:
    changed-files:
      - any-glob-to-any-file: '*'

'Type: Testing':
- any:
    changed-files:
      - any-glob-to-any-file: 'src/stratify/tests/*'
