# Reference
#   - https://github.com/actions/labeler

name: ci-label

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  PR_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
